locales: [pl, en, pt-pt]

#The amount in seconds beetween ram checks
#default = 600 [10 min]
ram-check-interval: 600
#the percentage level of ram usage needed to trigger the alarm
#ex.: 50 here will trigger alarm (send message to players 
#with sysinfo.alarm-recv permission) if RAM usage will be over 50%
#default = 90
ram-alarm-level: 90